name: vercel deployment
on: [push]
jobs: 
  eslint: 
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
          cache: 'npm'

      - name: Clean Install
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Build and Bundle
        run: npm run build
      
      
